name: image_similarity
channels:
- defaults
dependencies:
- python=3.6
- bz2file==0.98
- cython==0.29.*
- tensorflow==1.12.*
- scikit-learn==0.20.*
- matplotlib==3.0.*
- pandas==0.24.*
- pillow==5.4.*
- jupyter==1.0.*
